name: Python CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.10 '
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade pyserial
    - name: Install xvfb
      run: sudo apt-get install xvfb
    - name: Start xvfb
      run: |
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        export DISPLAY=:99    
    - name: Test with pytest
      run: |
        xvfb-run
        export DISPLAY=:99 
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & 
        pytest
